layout_spectrum: 0.048758251774263114
typography_spectrum: 0.25833726035301935
color:
  brandColors:
    - '#694264'
    - '#C4C5C0'
    - '#E7E3E1'
    - '#B58BAB'
    - '#CDA673'
  brandStrength: 0.31856253534260365
  lightness: 0.5622810096621956
  saturation: 0.8595447265257192
  rhythmicContrast: 0.22682616504231967
content_rating:
  adult: false
github: true
opengraph:
  appId: 'http://www.facebook.com/500019040'
analytics:
  google: UA-48971923-1
author:
  name: Dennis Brockman
  email: dennis@brockmans.org
  url: 'http://www.brockmans.org/rss.xml'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1b3e04a9-99c4-4d65-b3ad-97b01c278deb.png
name: Brockmans
url: 'https://brockmans.org'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: Because of you... (mission briefs)
    url: 'https://thegrid.ai/mission-59281'
    type: external
  - name: About us
    id: efb2f6c6-1243-447f-b59e-1fceca264511
    type: content
  - name: Lisa's blog (family & formation)
    url: 'https://thegrid.ai/family-82471'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/abdd5766-f389-459b-92cc-a359e7df6d7d.png
title: Brockmans
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/958b9134-d53e-478d-9298-1546869be0d7.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/958b9134-d53e-478d-9298-1546869be0d7.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: >-
  We come alongside people in their highs and lows in their spiritual journeys
  and offer them next steps in knowing and growing in Jesus.
purpose:
  - type: external
    url: 'http://give.cru.org/0258043'
    label: Give a gift to make disciples
