layout_spectrum: 0.04237988866865635
typography_spectrum: 0.4424648442274273
color:
  brandColors:
    - '#F4F4F4'
    - '#330205'
    - '#A90508'
    - '#0D8523'
    - '#FFD290'
  brandStrength: 0.6971572756975667
  lightness: 0.5265762901074705
  saturation: 0.676191111628501
  rhythmicContrast: 0.15816607051575093
content_rating:
  adult: false
github: true
opengraph:
  appId: 'http://www.facebook.com/500019040'
analytics:
  google: UA-48971923-1
author:
  name: Dennis Brockman
  email: dennis@brockmans.org
  url: 'http://www.brockmans.org/rss.xml'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1b3e04a9-99c4-4d65-b3ad-97b01c278deb.png
name: Brockmans
url: 'https://brockmans.org'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: About us
    id: efb2f6c6-1243-447f-b59e-1fceca264511
    type: content
  - name: Lisa's blog (family & formation)
    url: 'https://thegrid.ai/family-82471'
    type: external
  - name: Because of you... (mission briefs)
    url: 'https://thegrid.ai/mission-59281'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/abdd5766-f389-459b-92cc-a359e7df6d7d.png
title: Brockmans
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/575cf342-bfca-4544-910c-4a6acb0c8c65.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/575cf342-bfca-4544-910c-4a6acb0c8c65.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/f0e98d3a-158f-41e8-9083-6c300c8d983a.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/f0e98d3a-158f-41e8-9083-6c300c8d983a.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Uniting with Gospel Champions to make disciples of Jesus Christ.
purpose:
  - type: external
    url: 'http://give.cru.org/0258043'
    label: Give to make disciples
