layout_spectrum: 0.023419386022401477
typography_spectrum: 0.7005645538601877
color:
  brandColors:
    - '#04BFBF'
    - '#CAFCD8'
    - '#F7E967'
    - '#A9CF54'
    - '#588F27'
  brandStrength: 0.02525206107747658
  lightness: 0.13573403445893142
  saturation: 0.7750601061286018
  rhythmicContrast: 0.6637694221851186
coverPrefs:
  filter: false
content_rating:
  adult: false
github: true
opengraph:
  appId: 'http://www.facebook.com/500019040'
analytics:
  google: UA-48971923-1
author:
  name: Dennis Brockman
  email: dennis@brockmans.org
  url: 'http://www.brockmans.org/rss.xml'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1b3e04a9-99c4-4d65-b3ad-97b01c278deb.png
name: Brockmans
url: 'https://brockmans.org'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: Because of you... (mission briefs)
    url: 'https://thegrid.ai/mission-59281'
    type: external
  - name: About us
    id: efb2f6c6-1243-447f-b59e-1fceca264511
    type: content
  - name: Lisa's blog (family & formation)
    url: 'https://thegrid.ai/family-82471'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/abdd5766-f389-459b-92cc-a359e7df6d7d.png
title: Brockmans
content: []
description: >-
  We come alongside people in the highs and lows in their spiritual journeys and
  offer them next steps in knowing and growing with Jesus.
purpose:
  - type: external
    url: 'http://give.cru.org/0258043'
    label: Give a gift to make disciples
