typography_spectrum: 0.2527465097868981
content_rating:
  adult: false
color:
  brandColors:
    - '#E8E595'
    - '#D0A825'
    - '#40627C'
    - '#26393D'
    - '#FFFAE4'
  brandStrength: 0.3824362635997004
  lightness: 0.36903656644433147
  saturation: 0.8876855660812689
  rhythmicContrast: 0.6838488362132028
github: true
opengraph:
  appId: 'http://www.facebook.com/500019040'
layout_spectrum: 0.04327690474984079
analytics:
  google: UA-48971923-1
author:
  name: Dennis Brockman
  email: dennis@brockmans.org
  url: 'http://www.brockmans.org/rss.xml'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1b3e04a9-99c4-4d65-b3ad-97b01c278deb.png
name: Brockmans
url: 'https://brockmans.org'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: About us
    id: efb2f6c6-1243-447f-b59e-1fceca264511
    type: content
  - name: Because of you...
    id: 3b6af503-6ce5-448d-9396-6fc066a67a51
    type: content
  - name: Family on mission
    id: f0b92c0d-c6e2-4f38-9b4a-061125b44907
    type: content
  - name: Home
    url: 'https://brockmans.org'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/abdd5766-f389-459b-92cc-a359e7df6d7d.png
title: Brockmans
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/b77adb98-b05a-4b01-8980-3c78658d179f.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/b77adb98-b05a-4b01-8980-3c78658d179f.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Uniting with Gospel Champions to make disciples of Jesus Christ.
purpose:
  - type: external
    url: 'http://give.cru.org/0258043'
    label: Be our Gospel Champion
