layout_spectrum: 0.041925218004346045
typography_spectrum: 0.7729616803760724
color:
  brandColors:
    - '#0481B7'
    - '#2D490C'
    - '#2E004B'
    - '#FFF1FF'
    - '#88A0C2'
  brandStrength: 0.3531520383948884
  lightness: 0.8489575535304253
  saturation: 0.12529951041121737
  rhythmicContrast: 0.5558057066698624
content_rating:
  adult: false
github: true
opengraph:
  appId: 'http://www.facebook.com/500019040'
analytics:
  google: UA-48971923-1
author:
  name: Dennis Brockman
  email: dennis@brockmans.org
  url: 'http://www.brockmans.org/rss.xml'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1b3e04a9-99c4-4d65-b3ad-97b01c278deb.png
name: Brockmans
url: 'https://brockmans.org'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: About us
    id: efb2f6c6-1243-447f-b59e-1fceca264511
    type: content
  - name: Lisa's blog (family & formation)
    url: 'https://thegrid.ai/family-82471'
    type: external
  - name: Because of you... (mission briefs)
    url: 'https://thegrid.ai/mission-59281'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/abdd5766-f389-459b-92cc-a359e7df6d7d.png
title: Brockmans
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/b77adb98-b05a-4b01-8980-3c78658d179f.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/b77adb98-b05a-4b01-8980-3c78658d179f.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Uniting with Gospel Champions to make disciples of Jesus Christ.
purpose:
  - type: external
    url: 'http://give.cru.org/0258043'
    label: Give to be our Gospel Champion
