layout_spectrum: 0.04584671613160927
typography_spectrum: 0.2326963605605398
color:
  brandColors:
    - '#FF6600'
    - '#C13B00'
    - '#5E6D70'
    - '#424E4F'
    - '#1B1D1E'
  brandStrength: 0.009847342610672707
  lightness: 0.0579904694299186
  saturation: 0.9048272432413617
  rhythmicContrast: 0.7555134209463059
coverPrefs:
  filter: false
content_rating:
  adult: false
github: true
opengraph:
  appId: 'http://www.facebook.com/500019040'
analytics:
  google: UA-48971923-1
author:
  name: Dennis Brockman
  email: dennis@brockmans.org
  url: 'http://www.brockmans.org/rss.xml'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1b3e04a9-99c4-4d65-b3ad-97b01c278deb.png
name: Brockmans
url: 'https://brockmans.org'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: Because of you... (mission briefs)
    url: 'https://thegrid.ai/mission-59281'
    type: external
  - name: About us
    id: efb2f6c6-1243-447f-b59e-1fceca264511
    type: content
  - name: Lisa's blog (family & formation)
    url: 'https://thegrid.ai/family-82471'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/abdd5766-f389-459b-92cc-a359e7df6d7d.png
title: Brockmans
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FZK3-NsqpZWs%3Fstart%3D3%26feature%3Doembed%26start%3D3&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DZK3-NsqpZWs&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FZK3-NsqpZWs%2Fhqdefault.jpg&key=a715cf41cc93453ca338d350cd26f87b&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen="true"></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: Cru
          url: 'https://www.youtube.com/user/cruglobal'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vfl8qSV2F.ico'
        domain: youtu.be
      keywords:
        - community (website category)
        - cru (nonprofit organization)
        - relationship
        - christianity (religion)
      description: >-
        What happens when someone connects to a Cru community anywhere in the
        world? Just watch and see.
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=ZK3-NsqpZWs&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=ZK3-NsqpZWs&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=ZK3-NsqpZWs&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=ZK3-NsqpZWs&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=ZK3-NsqpZWs&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=ZK3-NsqpZWs'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=ZK3-NsqpZWs
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=ZK3-NsqpZWs
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://youtu.be/ZK3-NsqpZWs?t=3'
      title: What is community to Cru?
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: >-
  We come alongside people in the highs and lows in their spiritual journeys and
  offer them next steps in knowing and growing with Jesus.
purpose:
  - type: external
    url: 'http://give.cru.org/0258043'
    label: Give a gift to make disciples
